# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Prepare 
      - name: Installion
        run: sudo apt-get -y install cmake clang       

      # Run versioning command
      - name: Create cache version check
        run: |
          cmake -S . -B build_opt -DCMAKE_INSTALL_PREFIX=/opt/hep -DCMAKE_CXX_COMPILER=clang -DCMAKE_C_COMPILER=clang -DVERSIONING=On 
          echo "base_deps_version=`cat /opt/hep/versioning/base-deps.version`" >> $GITHUB_ENV
          echo "geant4_version=`cat /opt/hep/versioning/geant4.version`" >> $GITHUB_ENV
          echo "root_version=`cat /opt/hep/versioning/root.version`" >> $GITHUB_ENV
      
      # Check if there is a Cache available
      - name: Check for base cache
        id: cache-base
        uses: actions/cache@v3
        env:
          cache-name: base-deps
        with:
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.base_deps_version }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-${{ env.base_deps_version }}
          path: |
            /opt/hep/boost
            /opt/hep/eigen
            /opt/hep/pythia8
            /opt/hep/tbb
            /opt/hep/xercesc

      # Run the base build
      - if: ${{ steps.cache-base.outputs.cache-hit != 'true' }}
        name: Build base dependencies
        continue-on-error: true
        run: |
          cmake -S . -B build_opt -DCMAKE_INSTALL_PREFIX=/opt/hep -DCMAKE_CXX_COMPILER=clang -DCMAKE_C_COMPILER=clang -DVERSIONING=Off -DBUILD_BASE=On
          cmake --build build_opt

      # Check if there is a Cache available
      - name: Check for Geant4 cache
        id: cache-geant4
        uses: actions/cache@v3
        env:
          cache-name: geant4
        with:
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.geant4_version }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-${{ env.geant4_version }}
          path: |
            /opt/hep/geant4

      # Run the Geant4 build
      - if: ${{ steps.cache-geant4.outputs.cache-hit != 'true' }}
        name: Build Geant4
        continue-on-error: true        
        run: |
          cmake -S . -B build_opt -DCMAKE_INSTALL_PREFIX=/opt/hep -DCMAKE_CXX_COMPILER=clang -DCMAKE_C_COMPILER=clang -DVERSIONING=Off -DBUILD_BASE=Off -DBUILD_GEANT4=On
          cmake --build build_opt

      # Run the ROOT Build
      #- name: Build ROOT
      #  run: |
      #    cmake -S . -B build_opt -DCMAKE_INSTALL_PREFIX=/opt/hep -DCMAKE_CXX_COMPILER=clang -DCMAKE_C_COMPILER=clang -DBUILD_BASE=Off -DBUILD_GEANT4=Off -DBUILD_ROOT=On && cmake --build build_opt

      # Upload the artifacts
      # - name: Archive artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: externals-opt
      #     path: |
      #       /opt/hep
